- name: Copy SolarWinds installer from datastore to VM
  community.vmware.vmware_guest_file_operation:
    hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
    username: "{{ lookup('env', 'VMWARE_USER') }}"
    password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
    validate_certs: false
    datacenter: "{{ vcenter_datacenter }}"
    vm_name: "{{ provisioned_hostname }}"
    datastore: "{{ vcenter_datastore }}"
    src: >
      [{{ vcenter_datastore }}]
      {{ solarwinds_datastore_path }}/{{ solarwinds_installer_name }}
    dest: "{{ solarwinds_installer_dest }}"
    operation: copy